name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache4        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    # Make deploy depend on test to run first.
    needs: test
    runs-on: ubuntu-latest
    # generates a job level output for the build job based on the step output that can be passed into other jobs e.g deploy
    outputs:
      # References the output of step with id=publish below and corresponding value of key value 
      #  'script-file' which is temporarily stored in $GITHUB_OUTPUT so it can be retrieved and stored by this step
      script-file: ${{ steps.publish.outputs.script-file}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS filename
        id: publish
        # the step finds the built JavaScript file (whose name changes with every build) and saves its filename into a variable named script-file
        # $GITHUB_OUTPUT is a special environment variable that github uses to store output between github steps. 
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #  dist
          #  package.json
  deploy:
    # Make deploy depend on test to run first.
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        # Download the artifacts uploaded in the build job
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file}}"
      - name: Deploying
        run: echo "Deploying.."
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
